---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets  
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: "sealed-secrets-deployment-succeeded"
    notifications.argoproj.io/subscribe.on-health-degraded.grafana: "sealed-secrets-degraded"
    notifications.argoproj.io/subscribe.on-sync-failed.grafana: "sealed-secrets-sync-failed"
    notifications.argoproj.io/subscribe.on-deployed.grafana: "sealed-secrets-deployed"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: "sealed-secrets-status-unknown"
    recipients.argocd-notifications.argoproj.io: "slack:platform-alerts"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: git@github.com:notifi-network/infra.git
    path: 20-platform/services/sealed-secrets/deploy
    targetRevision: HEAD
    helm:
      releaseName: sealed-secrets
      valueFiles:
        - values.yaml
        - overlays/local/values-local.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: "cert-manager-deployment-succeeded"
    notifications.argoproj.io/subscribe.on-health-degraded.grafana: "cert-manager-degraded"
    notifications.argoproj.io/subscribe.on-sync-failed.grafana: "cert-manager-sync-failed"
    notifications.argoproj.io/subscribe.on-deployed.grafana: "cert-manager-deployed"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.grafana: "cert-manager-status-unknown"
    recipients.argocd-notifications.argoproj.io: "slack:platform-alerts"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  source:
    repoURL: git@github.com:notifi-network/infra.git
    path: 20-platform/services/cert-manager/deploy
    targetRevision: HEAD
    helm:
      releaseName: cert-manager
      valueFiles:
        - values.yaml
        - overlays/local/values-local.yaml