apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    knative-serving-injection: enabled
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
  workloads:
    - name: activator
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    - name: autoscaler
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    - name: autoscaler-hpa
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    - name: cleanup-serving-serving
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    - name: controller
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
    - name: webhook
      # resources: {}
      tolerations:
        - key: "observability"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "rabbitmq"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  ingress:
    kourier:
      enabled: true
    istio:
      enabled: false
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
