apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grafana-mcp
  name: grafana-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-mcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-mcp
    spec:
      containers:
      - env:
        - name: GRAFANA_URL
          value: http://prometheus-grafana.prometheus.svc.cluster.local:80
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: grafana-api-key
        image: mcp/grafana:latest
        imagePullPolicy: IfNotPresent
        name: server
        ports:
        - containerPort: 8000
          name: http
        # TODO: Refactor and add resources
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 256Mi
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi