apiVersion: v1
kind: Secret
metadata:
  name: grafana-api-key
  namespace: grafana-mcp
  labels:
    app.kubernetes.io/name: grafana-mcp
    app.kubernetes.io/component: credentials
stringData:
  api-key: "aaaaaaaaaaaaaaaa"
  # TODO: Automate creation of API key and use SEALED SECRETS
  # NOTE: Do the same automation for service accounts in grafana
