apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana-mcp
  name: grafana-mcp
  namespace: grafana-mcp
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: grafana-mcp