apiVersion: v2
name: alloy
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "0.10.1"

dependencies:
  - name: alloy
    version: 0.10.1
    repository: https://grafana.github.io/helm-charts