apiVersion: v2
name: linkerd
description: A Helm chart for deploying the linkerd service

type: application

version: 0.1.0

appVersion: "6.25.0"

dependencies:
  - name: linkerd
    version: 6.25.0
    repository: https://linkerd.github.io/helm-charts