apiVersion: v2
name: grafana-mcp
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "0.10.1"

# TODO: Check for a official chart in the future.
# dependencies:
#   - name: grafana-mcp
#     version: 0.10.1
#     repository: https://grafana.github.io/helm-charts