apiVersion: v2
name: alloy
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "0.10.1"

dependencies:
  - name: sealed-secrets
    version: 2.17.2
    repository: https://bitnami-labs.github.io/sealed-secrets